a = int(input())
b = int(input())
c = int(input())
r = a * b * c
l = str(r)
print(l.count("0"))
print(l.count("1"))
print(l.count("2"))
print(l.count("3"))
print(l.count("4"))
print(l.count("5"))
print(l.count("6"))
print(l.count("7"))
print(l.count("8"))
print(l.count("9"))